{% set version = "0.21" %}

package:
  name: libgdsii
  version: {{ version }}

source:
  url: https://github.com/HomerReid/libGDSII/releases/download/v{{ version }}/libgdsii-{{ version }}.tar.gz
  sha256: 31c90a4fb699746d051c0c597ef0543889c9f17b2a711fed398756ac4f1b1f4c

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - gnuconfig  # [unix]
    - make

test:
  source_files:
    - examples/bend-flux/bend-flux.gds
  commands:
    - test -f ${PREFIX}/lib/libGDSII${SHLIB_EXT}
    - GDSIIConvert --gmsh examples/bend-flux/bend-flux.gds

about:
  home: http:/github.com/HomerReid/libGDSII
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: C++ library and command-line utility for reading GDSII geometry files
  doc_url: https://github.com/HomerReid/libGDSII/tree/master/README.md
  dev_url: https://github.com/HomerReid/libGDSII

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
