travis:
  secure:
    BINSTAR_TOKEN: pwaxmRFZm2TIcV0WTTpzboYiCQH4e1bXo18V3n1r/b/EMVK3SXMhZBdbxogGrjuNFTxF2w2kX5OtJaaybBWHwp96xnLZQfF79T7FVbzAkjvcjVe02aHrDj7EbfGu1ucTTKN5/ED95g00c6UsWi1pgbyOa6eq/BfZkz9vd7H+LlgYBX3NTjqh78SggyCokOIhMrK1ZKqRi2qsfEbJo5nmeyOyc4dBv7OY4pEJQH0iygxE98AItwFegBReO/0Io6d1n2pBzfnDy+//5sc8hjSYCD1QeLTfn56CgL0rZQl2+fIyyuQ+SvT/FYZ0wO/5X9yt22jDkvHfRPJZkcwbWIIC/7nYyMGn+5Dr+y4TMZt27FW5pYexpOs5CfC4HeFWcCCFWIfGRojJ5VMwmmEzocgKsW+b+wWeYvET0pYkPn5z0je1ad8UYdNuNpM6Te4/cfvZFXpxNyT6iYkS0f76TRzD6Gi7qrTh2XCFND4EJGIr+/A6ApLjSn9HJW35rLNWUxbftBqMFCPbq8ybj/KbFePCG8HduRMeEvwxRmVD/uOHGcEIQCagu9Wa5KLRwXAJRghRonAg42nzH59g0YvDjsgoHFBbattzcO0ahef1Od/KMLe5pxk0sP+Nh6UElkaLkYUev01LEY4CxhsD1QE7hcyRYfh7H2ksjGDBNGQdvJ/oonE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
